// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart.sql

package sqlc

import (
	"context"
)

const addToCart = `-- name: AddToCart :one
INSERT INTO carts (user_id, product_id, quantity, selected)
VALUES ($1, $2, $3, TRUE)
    ON CONFLICT (user_id, product_id)
  DO UPDATE SET
    quantity = carts.quantity + EXCLUDED.quantity,
             updated_at = NOW()
             RETURNING id, user_id, product_id, quantity, selected, created_at, updated_at, deleted_at
`

type AddToCartParams struct {
	UserID    int64 `db:"user_id" json:"user_id"`
	ProductID int64 `db:"product_id" json:"product_id"`
	Quantity  int32 `db:"quantity" json:"quantity"`
}

func (q *Queries) AddToCart(ctx context.Context, arg AddToCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, addToCart, arg.UserID, arg.ProductID, arg.Quantity)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.Selected,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const clearCart = `-- name: ClearCart :exec
UPDATE carts
SET deleted_at = NOW()
WHERE user_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, clearCart, userID)
	return err
}

const countCartItems = `-- name: CountCartItems :one
SELECT COUNT(*) FROM carts
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountCartItems(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCartItems, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
UPDATE carts
SET deleted_at = NOW()
WHERE id = $1 AND user_id = $2
`

type DeleteCartItemParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error {
	_, err := q.db.Exec(ctx, deleteCartItem, arg.ID, arg.UserID)
	return err
}

const getCartByUserID = `-- name: GetCartByUserID :many
SELECT id, user_id, product_id, quantity, selected, created_at, updated_at, deleted_at FROM carts
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetCartByUserID(ctx context.Context, userID int64) ([]Cart, error) {
	rows, err := q.db.Query(ctx, getCartByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cart{}
	for rows.Next() {
		var i Cart
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Quantity,
			&i.Selected,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCartItem = `-- name: GetCartItem :one
SELECT id, user_id, product_id, quantity, selected, created_at, updated_at, deleted_at FROM carts
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
    LIMIT 1
`

type GetCartItemParams struct {
	ID     int64 `db:"id" json:"id"`
	UserID int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) GetCartItem(ctx context.Context, arg GetCartItemParams) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartItem, arg.ID, arg.UserID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.Selected,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCartItemByProduct = `-- name: GetCartItemByProduct :one
SELECT id, user_id, product_id, quantity, selected, created_at, updated_at, deleted_at FROM carts
WHERE user_id = $1 AND product_id = $2 AND deleted_at IS NULL
    LIMIT 1
`

type GetCartItemByProductParams struct {
	UserID    int64 `db:"user_id" json:"user_id"`
	ProductID int64 `db:"product_id" json:"product_id"`
}

func (q *Queries) GetCartItemByProduct(ctx context.Context, arg GetCartItemByProductParams) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartItemByProduct, arg.UserID, arg.ProductID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.Selected,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSelectedCartItems = `-- name: GetSelectedCartItems :many
SELECT id, user_id, product_id, quantity, selected, created_at, updated_at, deleted_at FROM carts
WHERE user_id = $1 AND selected = TRUE AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetSelectedCartItems(ctx context.Context, userID int64) ([]Cart, error) {
	rows, err := q.db.Query(ctx, getSelectedCartItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cart{}
	for rows.Next() {
		var i Cart
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Quantity,
			&i.Selected,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAllCartSelected = `-- name: UpdateAllCartSelected :exec
UPDATE carts
SET
    selected = $1,
    updated_at = NOW()
WHERE user_id = $2 AND deleted_at IS NULL
`

type UpdateAllCartSelectedParams struct {
	Selected bool  `db:"selected" json:"selected"`
	UserID   int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateAllCartSelected(ctx context.Context, arg UpdateAllCartSelectedParams) error {
	_, err := q.db.Exec(ctx, updateAllCartSelected, arg.Selected, arg.UserID)
	return err
}

const updateCartQuantity = `-- name: UpdateCartQuantity :exec
UPDATE carts
SET
    quantity = $1,
    updated_at = NOW()
WHERE id = $2 AND user_id = $3 AND deleted_at IS NULL
`

type UpdateCartQuantityParams struct {
	Quantity int32 `db:"quantity" json:"quantity"`
	ID       int64 `db:"id" json:"id"`
	UserID   int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateCartQuantity(ctx context.Context, arg UpdateCartQuantityParams) error {
	_, err := q.db.Exec(ctx, updateCartQuantity, arg.Quantity, arg.ID, arg.UserID)
	return err
}

const updateCartSelected = `-- name: UpdateCartSelected :exec
UPDATE carts
SET
    selected = $1,
    updated_at = NOW()
WHERE id = $2 AND user_id = $3 AND deleted_at IS NULL
`

type UpdateCartSelectedParams struct {
	Selected bool  `db:"selected" json:"selected"`
	ID       int64 `db:"id" json:"id"`
	UserID   int64 `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateCartSelected(ctx context.Context, arg UpdateCartSelectedParams) error {
	_, err := q.db.Exec(ctx, updateCartSelected, arg.Selected, arg.ID, arg.UserID)
	return err
}
