// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package sqlc

import (
	"context"
)

const countCategoryChildren = `-- name: CountCategoryChildren :one
SELECT COUNT(*) FROM categories
WHERE parent_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountCategoryChildren(ctx context.Context, parentID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoryChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProductsByCategory = `-- name: CountProductsByCategory :one
SELECT COUNT(*) FROM products
WHERE category_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountProductsByCategory(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProductsByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    name,
    slug,
    parent_id,
    icon,
    sort,
    level,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, name, slug, parent_id, icon, sort, level, is_active, created_at, updated_at, deleted_at
`

type CreateCategoryParams struct {
	Name     string  `db:"name" json:"name"`
	Slug     *string `db:"slug" json:"slug"`
	ParentID *int64  `db:"parent_id" json:"parent_id"`
	Icon     *string `db:"icon" json:"icon"`
	Sort     int32   `db:"sort" json:"sort"`
	Level    int16   `db:"level" json:"level"`
	IsActive bool    `db:"is_active" json:"is_active"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.Slug,
		arg.ParentID,
		arg.Icon,
		arg.Sort,
		arg.Level,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ParentID,
		&i.Icon,
		&i.Sort,
		&i.Level,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
UPDATE categories
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, slug, parent_id, icon, sort, level, is_active, created_at, updated_at, deleted_at FROM categories
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ParentID,
		&i.Icon,
		&i.Sort,
		&i.Level,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug, parent_id, icon, sort, level, is_active, created_at, updated_at, deleted_at FROM categories
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug *string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ParentID,
		&i.Icon,
		&i.Sort,
		&i.Level,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryChildren = `-- name: GetCategoryChildren :many
SELECT id, name, slug, parent_id, icon, sort, level, is_active, created_at, updated_at, deleted_at FROM categories
WHERE parent_id = $1
  AND deleted_at IS NULL
ORDER BY sort, id
`

func (q *Queries) GetCategoryChildren(ctx context.Context, parentID *int64) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategoryChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
			&i.Icon,
			&i.Sort,
			&i.Level,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRootCategories = `-- name: GetRootCategories :many
SELECT id, name, slug, parent_id, icon, sort, level, is_active, created_at, updated_at, deleted_at FROM categories
WHERE parent_id IS NULL
  AND deleted_at IS NULL
  AND is_active = true
ORDER BY sort, id
`

func (q *Queries) GetRootCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, getRootCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
			&i.Icon,
			&i.Sort,
			&i.Level,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, parent_id, icon, sort, level, is_active, created_at, updated_at, deleted_at FROM categories
WHERE deleted_at IS NULL
  AND ($1::boolean IS NULL OR is_active = $1)
ORDER BY sort, id
`

func (q *Queries) ListCategories(ctx context.Context, dollar_1 bool) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
			&i.Icon,
			&i.Sort,
			&i.Level,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories
SET
    name = COALESCE($1, name),
    slug = COALESCE($2, slug),
    parent_id = COALESCE($3, parent_id),
    icon = COALESCE($4, icon),
    sort = COALESCE($5, sort),
    is_active = COALESCE($6, is_active),
    updated_at = NOW()
WHERE id = $7 AND deleted_at IS NULL
`

type UpdateCategoryParams struct {
	Name     *string `db:"name" json:"name"`
	Slug     *string `db:"slug" json:"slug"`
	ParentID *int64  `db:"parent_id" json:"parent_id"`
	Icon     *string `db:"icon" json:"icon"`
	Sort     *int32  `db:"sort" json:"sort"`
	IsActive *bool   `db:"is_active" json:"is_active"`
	ID       int64   `db:"id" json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.Exec(ctx, updateCategory,
		arg.Name,
		arg.Slug,
		arg.ParentID,
		arg.Icon,
		arg.Sort,
		arg.IsActive,
		arg.ID,
	)
	return err
}
