// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddToCart(ctx context.Context, arg AddToCartParams) (Cart, error)
	BlockSession(ctx context.Context, id uuid.UUID) error
	CleanExpiredSessions(ctx context.Context) error
	ClearCart(ctx context.Context, userID int64) error
	CountCartItems(ctx context.Context, userID int64) (int64, error)
	CountProducts(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	// Product Images
	CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (VerificationCode, error)
	DecrementProductStock(ctx context.Context, arg DecrementProductStockParams) error
	DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error
	DeleteExpiredCodes(ctx context.Context) error
	DeleteProduct(ctx context.Context, id int64) error
	DeleteProductImage(ctx context.Context, id int64) error
	DeleteProductImages(ctx context.Context, productID int64) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserSessions(ctx context.Context, userID int64) error
	GetCartByUserID(ctx context.Context, userID int64) ([]Cart, error)
	GetCartItem(ctx context.Context, arg GetCartItemParams) (Cart, error)
	GetCartItemByProduct(ctx context.Context, arg GetCartItemByProductParams) (Cart, error)
	GetLatestVerificationCode(ctx context.Context, arg GetLatestVerificationCodeParams) (VerificationCode, error)
	GetProductByID(ctx context.Context, id int64) (Product, error)
	GetProductImages(ctx context.Context, productID int64) ([]ProductImage, error)
	GetProductMainImage(ctx context.Context, productID int64) (ProductImage, error)
	GetSelectedCartItems(ctx context.Context, userID int64) ([]Cart, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByPhone(ctx context.Context, phone *string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserSessions(ctx context.Context, userID int64) ([]Session, error)
	GetVerificationCode(ctx context.Context, arg GetVerificationCodeParams) (VerificationCode, error)
	IncrementProductSales(ctx context.Context, arg IncrementProductSalesParams) error
	IncrementProductViews(ctx context.Context, id int64) error
	ListFeaturedProducts(ctx context.Context, arg ListFeaturedProductsParams) ([]Product, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]Product, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkCodeAsUsed(ctx context.Context, id int64) error
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	UpdateAllCartSelected(ctx context.Context, arg UpdateAllCartSelectedParams) error
	UpdateCartQuantity(ctx context.Context, arg UpdateCartQuantityParams) error
	UpdateCartSelected(ctx context.Context, arg UpdateCartSelectedParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) error
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	VerifyUserEmail(ctx context.Context, id int64) error
	VerifyUserPhone(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
