// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	"gomall/utils/types"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, email, phone, password, nickname, avatar, gender
) VALUES (
             $1, $2, $3, $4, $5, $6, $7
         )
    RETURNING id, username, email, phone, password, nickname, avatar, gender, birthday, status, is_email_verified, is_phone_verified, last_login_at, last_login_ip, password_changed_at, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Username string  `db:"username" json:"username"`
	Email    string  `db:"email" json:"email"`
	Phone    *string `db:"phone" json:"phone"`
	Password string  `db:"password" json:"password"`
	Nickname *string `db:"nickname" json:"nickname"`
	Avatar   *string `db:"avatar" json:"avatar"`
	Gender   string  `db:"gender" json:"gender"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.Phone,
		arg.Password,
		arg.Nickname,
		arg.Avatar,
		arg.Gender,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Nickname,
		&i.Avatar,
		&i.Gender,
		&i.Birthday,
		&i.Status,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, phone, password, nickname, avatar, gender, birthday, status, is_email_verified, is_phone_verified, last_login_at, last_login_ip, password_changed_at, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
    LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Nickname,
		&i.Avatar,
		&i.Gender,
		&i.Birthday,
		&i.Status,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, phone, password, nickname, avatar, gender, birthday, status, is_email_verified, is_phone_verified, last_login_at, last_login_ip, password_changed_at, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
    LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Nickname,
		&i.Avatar,
		&i.Gender,
		&i.Birthday,
		&i.Status,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, username, email, phone, password, nickname, avatar, gender, birthday, status, is_email_verified, is_phone_verified, last_login_at, last_login_ip, password_changed_at, created_at, updated_at, deleted_at FROM users
WHERE phone = $1 AND deleted_at IS NULL
    LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Nickname,
		&i.Avatar,
		&i.Gender,
		&i.Birthday,
		&i.Status,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, phone, password, nickname, avatar, gender, birthday, status, is_email_verified, is_phone_verified, last_login_at, last_login_ip, password_changed_at, created_at, updated_at, deleted_at FROM users
WHERE username = $1 AND deleted_at IS NULL
    LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Phone,
		&i.Password,
		&i.Nickname,
		&i.Avatar,
		&i.Gender,
		&i.Birthday,
		&i.Status,
		&i.IsEmailVerified,
		&i.IsPhoneVerified,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, phone, password, nickname, avatar, gender, birthday, status, is_email_verified, is_phone_verified, last_login_at, last_login_ip, password_changed_at, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
    LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Phone,
			&i.Password,
			&i.Nickname,
			&i.Avatar,
			&i.Gender,
			&i.Birthday,
			&i.Status,
			&i.IsEmailVerified,
			&i.IsPhoneVerified,
			&i.LastLoginAt,
			&i.LastLoginIp,
			&i.PasswordChangedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
    nickname = COALESCE($1, nickname),
    avatar = COALESCE($2, avatar),
    gender = COALESCE($3, gender),
    birthday = COALESCE($4, birthday),
    updated_at = NOW()
WHERE id = $5 AND deleted_at IS NULL
`

type UpdateUserParams struct {
	Nickname *string        `db:"nickname" json:"nickname"`
	Avatar   *string        `db:"avatar" json:"avatar"`
	Gender   *string        `db:"gender" json:"gender"`
	Birthday types.NullTime `db:"birthday" json:"birthday"`
	ID       int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Nickname,
		arg.Avatar,
		arg.Gender,
		arg.Birthday,
		arg.ID,
	)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET
    last_login_at = $1,
    last_login_ip = $2,
    updated_at = NOW()
WHERE id = $3 AND deleted_at IS NULL
`

type UpdateUserLastLoginParams struct {
	LastLoginAt types.NullTime `db:"last_login_at" json:"last_login_at"`
	LastLoginIp *string        `db:"last_login_ip" json:"last_login_ip"`
	ID          int64          `db:"id" json:"id"`
}

func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, arg.LastLoginAt, arg.LastLoginIp, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET
    password = $1,
    password_changed_at = NOW(),
    updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	Password string `db:"password" json:"password"`
	ID       int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.Password, arg.ID)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET
    status = $1,
    updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateUserStatusParams struct {
	Status string `db:"status" json:"status"`
	ID     int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.Status, arg.ID)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users
SET
    is_email_verified = TRUE,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, id)
	return err
}

const verifyUserPhone = `-- name: VerifyUserPhone :exec
UPDATE users
SET
    is_phone_verified = TRUE,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) VerifyUserPhone(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, verifyUserPhone, id)
	return err
}
