// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification_code.sql

package sqlc

import (
	"context"
	"time"
)

const createVerificationCode = `-- name: CreateVerificationCode :one
INSERT INTO verification_codes (
  user_id, email, code, type, expires_at
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, user_id, email, code, type, is_used, expires_at, created_at
`

type CreateVerificationCodeParams struct {
	UserID    int64     `db:"user_id" json:"user_id"`
	Email     string    `db:"email" json:"email"`
	Code      string    `db:"code" json:"code"`
	Type      string    `db:"type" json:"type"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, createVerificationCode,
		arg.UserID,
		arg.Email,
		arg.Code,
		arg.Type,
		arg.ExpiresAt,
	)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Code,
		&i.Type,
		&i.IsUsed,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredCodes = `-- name: DeleteExpiredCodes :exec
DELETE FROM verification_codes
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredCodes)
	return err
}

const getLatestVerificationCode = `-- name: GetLatestVerificationCode :one
SELECT id, user_id, email, code, type, is_used, expires_at, created_at FROM verification_codes
WHERE email = $1 AND type = $2 AND is_used = FALSE
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestVerificationCodeParams struct {
	Email string `db:"email" json:"email"`
	Type  string `db:"type" json:"type"`
}

func (q *Queries) GetLatestVerificationCode(ctx context.Context, arg GetLatestVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getLatestVerificationCode, arg.Email, arg.Type)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Code,
		&i.Type,
		&i.IsUsed,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVerificationCode = `-- name: GetVerificationCode :one
SELECT id, user_id, email, code, type, is_used, expires_at, created_at FROM verification_codes
WHERE email = $1 AND code = $2 AND type = $3 AND is_used = FALSE
LIMIT 1
`

type GetVerificationCodeParams struct {
	Email string `db:"email" json:"email"`
	Code  string `db:"code" json:"code"`
	Type  string `db:"type" json:"type"`
}

func (q *Queries) GetVerificationCode(ctx context.Context, arg GetVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getVerificationCode, arg.Email, arg.Code, arg.Type)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Code,
		&i.Type,
		&i.IsUsed,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const markCodeAsUsed = `-- name: MarkCodeAsUsed :exec
UPDATE verification_codes
SET is_used = TRUE
WHERE id = $1
`

func (q *Queries) MarkCodeAsUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markCodeAsUsed, id)
	return err
}
