// Code generated by MockGen. DO NOT EDIT.
// Source: gomall/db/sqlc (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -package mockdb -destination db/mock/store.go gomall/db/sqlc Store
//

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	sqlc "gomall/db/sqlc"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddToCart mocks base method.
func (m *MockStore) AddToCart(ctx context.Context, arg sqlc.AddToCartParams) (sqlc.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToCart", ctx, arg)
	ret0, _ := ret[0].(sqlc.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddToCart indicates an expected call of AddToCart.
func (mr *MockStoreMockRecorder) AddToCart(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToCart", reflect.TypeOf((*MockStore)(nil).AddToCart), ctx, arg)
}

// BlockSession mocks base method.
func (m *MockStore) BlockSession(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlockSession indicates an expected call of BlockSession.
func (mr *MockStoreMockRecorder) BlockSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockSession", reflect.TypeOf((*MockStore)(nil).BlockSession), ctx, id)
}

// CleanExpiredSessions mocks base method.
func (m *MockStore) CleanExpiredSessions(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanExpiredSessions", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanExpiredSessions indicates an expected call of CleanExpiredSessions.
func (mr *MockStoreMockRecorder) CleanExpiredSessions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanExpiredSessions", reflect.TypeOf((*MockStore)(nil).CleanExpiredSessions), ctx)
}

// ClearCart mocks base method.
func (m *MockStore) ClearCart(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearCart", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearCart indicates an expected call of ClearCart.
func (mr *MockStoreMockRecorder) ClearCart(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCart", reflect.TypeOf((*MockStore)(nil).ClearCart), ctx, userID)
}

// CountCartItems mocks base method.
func (m *MockStore) CountCartItems(ctx context.Context, userID int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCartItems", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountCartItems indicates an expected call of CountCartItems.
func (mr *MockStoreMockRecorder) CountCartItems(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCartItems", reflect.TypeOf((*MockStore)(nil).CountCartItems), ctx, userID)
}

// CountProducts mocks base method.
func (m *MockStore) CountProducts(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountProducts", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountProducts indicates an expected call of CountProducts.
func (mr *MockStoreMockRecorder) CountProducts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountProducts", reflect.TypeOf((*MockStore)(nil).CountProducts), ctx)
}

// CountUsers mocks base method.
func (m *MockStore) CountUsers(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockStoreMockRecorder) CountUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockStore)(nil).CountUsers), ctx)
}

// CreateProduct mocks base method.
func (m *MockStore) CreateProduct(ctx context.Context, arg sqlc.CreateProductParams) (sqlc.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", ctx, arg)
	ret0, _ := ret[0].(sqlc.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockStoreMockRecorder) CreateProduct(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockStore)(nil).CreateProduct), ctx, arg)
}

// CreateProductImage mocks base method.
func (m *MockStore) CreateProductImage(ctx context.Context, arg sqlc.CreateProductImageParams) (sqlc.ProductImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProductImage", ctx, arg)
	ret0, _ := ret[0].(sqlc.ProductImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProductImage indicates an expected call of CreateProductImage.
func (mr *MockStoreMockRecorder) CreateProductImage(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProductImage", reflect.TypeOf((*MockStore)(nil).CreateProductImage), ctx, arg)
}

// CreateSession mocks base method.
func (m *MockStore) CreateSession(ctx context.Context, arg sqlc.CreateSessionParams) (sqlc.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, arg)
	ret0, _ := ret[0].(sqlc.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockStoreMockRecorder) CreateSession(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockStore)(nil).CreateSession), ctx, arg)
}

// CreateUser mocks base method.
func (m *MockStore) CreateUser(ctx context.Context, arg sqlc.CreateUserParams) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, arg)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStoreMockRecorder) CreateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStore)(nil).CreateUser), ctx, arg)
}

// CreateVerificationCode mocks base method.
func (m *MockStore) CreateVerificationCode(ctx context.Context, arg sqlc.CreateVerificationCodeParams) (sqlc.VerificationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVerificationCode", ctx, arg)
	ret0, _ := ret[0].(sqlc.VerificationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVerificationCode indicates an expected call of CreateVerificationCode.
func (mr *MockStoreMockRecorder) CreateVerificationCode(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVerificationCode", reflect.TypeOf((*MockStore)(nil).CreateVerificationCode), ctx, arg)
}

// DecrementProductStock mocks base method.
func (m *MockStore) DecrementProductStock(ctx context.Context, arg sqlc.DecrementProductStockParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementProductStock", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementProductStock indicates an expected call of DecrementProductStock.
func (mr *MockStoreMockRecorder) DecrementProductStock(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementProductStock", reflect.TypeOf((*MockStore)(nil).DecrementProductStock), ctx, arg)
}

// DeleteCartItem mocks base method.
func (m *MockStore) DeleteCartItem(ctx context.Context, arg sqlc.DeleteCartItemParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCartItem", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCartItem indicates an expected call of DeleteCartItem.
func (mr *MockStoreMockRecorder) DeleteCartItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCartItem", reflect.TypeOf((*MockStore)(nil).DeleteCartItem), ctx, arg)
}

// DeleteExpiredCodes mocks base method.
func (m *MockStore) DeleteExpiredCodes(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredCodes", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredCodes indicates an expected call of DeleteExpiredCodes.
func (mr *MockStoreMockRecorder) DeleteExpiredCodes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredCodes", reflect.TypeOf((*MockStore)(nil).DeleteExpiredCodes), ctx)
}

// DeleteProduct mocks base method.
func (m *MockStore) DeleteProduct(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockStoreMockRecorder) DeleteProduct(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockStore)(nil).DeleteProduct), ctx, id)
}

// DeleteProductImage mocks base method.
func (m *MockStore) DeleteProductImage(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductImage", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProductImage indicates an expected call of DeleteProductImage.
func (mr *MockStoreMockRecorder) DeleteProductImage(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductImage", reflect.TypeOf((*MockStore)(nil).DeleteProductImage), ctx, id)
}

// DeleteProductImages mocks base method.
func (m *MockStore) DeleteProductImages(ctx context.Context, productID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProductImages", ctx, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProductImages indicates an expected call of DeleteProductImages.
func (mr *MockStoreMockRecorder) DeleteProductImages(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProductImages", reflect.TypeOf((*MockStore)(nil).DeleteProductImages), ctx, productID)
}

// DeleteSession mocks base method.
func (m *MockStore) DeleteSession(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockStoreMockRecorder) DeleteSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockStore)(nil).DeleteSession), ctx, id)
}

// DeleteUser mocks base method.
func (m *MockStore) DeleteUser(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockStoreMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockStore)(nil).DeleteUser), ctx, id)
}

// DeleteUserSessions mocks base method.
func (m *MockStore) DeleteUserSessions(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserSessions", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserSessions indicates an expected call of DeleteUserSessions.
func (mr *MockStoreMockRecorder) DeleteUserSessions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserSessions", reflect.TypeOf((*MockStore)(nil).DeleteUserSessions), ctx, userID)
}

// ExecTx mocks base method.
func (m *MockStore) ExecTx(ctx context.Context, fn func(sqlc.Querier) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecTx indicates an expected call of ExecTx.
func (mr *MockStoreMockRecorder) ExecTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecTx", reflect.TypeOf((*MockStore)(nil).ExecTx), ctx, fn)
}

// GetCartByUserID mocks base method.
func (m *MockStore) GetCartByUserID(ctx context.Context, userID int64) ([]sqlc.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartByUserID", ctx, userID)
	ret0, _ := ret[0].([]sqlc.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartByUserID indicates an expected call of GetCartByUserID.
func (mr *MockStoreMockRecorder) GetCartByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartByUserID", reflect.TypeOf((*MockStore)(nil).GetCartByUserID), ctx, userID)
}

// GetCartItem mocks base method.
func (m *MockStore) GetCartItem(ctx context.Context, arg sqlc.GetCartItemParams) (sqlc.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartItem", ctx, arg)
	ret0, _ := ret[0].(sqlc.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartItem indicates an expected call of GetCartItem.
func (mr *MockStoreMockRecorder) GetCartItem(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartItem", reflect.TypeOf((*MockStore)(nil).GetCartItem), ctx, arg)
}

// GetCartItemByProduct mocks base method.
func (m *MockStore) GetCartItemByProduct(ctx context.Context, arg sqlc.GetCartItemByProductParams) (sqlc.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartItemByProduct", ctx, arg)
	ret0, _ := ret[0].(sqlc.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartItemByProduct indicates an expected call of GetCartItemByProduct.
func (mr *MockStoreMockRecorder) GetCartItemByProduct(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartItemByProduct", reflect.TypeOf((*MockStore)(nil).GetCartItemByProduct), ctx, arg)
}

// GetLatestVerificationCode mocks base method.
func (m *MockStore) GetLatestVerificationCode(ctx context.Context, arg sqlc.GetLatestVerificationCodeParams) (sqlc.VerificationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestVerificationCode", ctx, arg)
	ret0, _ := ret[0].(sqlc.VerificationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestVerificationCode indicates an expected call of GetLatestVerificationCode.
func (mr *MockStoreMockRecorder) GetLatestVerificationCode(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestVerificationCode", reflect.TypeOf((*MockStore)(nil).GetLatestVerificationCode), ctx, arg)
}

// GetProductByID mocks base method.
func (m *MockStore) GetProductByID(ctx context.Context, id int64) (sqlc.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", ctx, id)
	ret0, _ := ret[0].(sqlc.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockStoreMockRecorder) GetProductByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockStore)(nil).GetProductByID), ctx, id)
}

// GetProductImages mocks base method.
func (m *MockStore) GetProductImages(ctx context.Context, productID int64) ([]sqlc.ProductImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductImages", ctx, productID)
	ret0, _ := ret[0].([]sqlc.ProductImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductImages indicates an expected call of GetProductImages.
func (mr *MockStoreMockRecorder) GetProductImages(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductImages", reflect.TypeOf((*MockStore)(nil).GetProductImages), ctx, productID)
}

// GetProductMainImage mocks base method.
func (m *MockStore) GetProductMainImage(ctx context.Context, productID int64) (sqlc.ProductImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductMainImage", ctx, productID)
	ret0, _ := ret[0].(sqlc.ProductImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductMainImage indicates an expected call of GetProductMainImage.
func (mr *MockStoreMockRecorder) GetProductMainImage(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductMainImage", reflect.TypeOf((*MockStore)(nil).GetProductMainImage), ctx, productID)
}

// GetSelectedCartItems mocks base method.
func (m *MockStore) GetSelectedCartItems(ctx context.Context, userID int64) ([]sqlc.Cart, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSelectedCartItems", ctx, userID)
	ret0, _ := ret[0].([]sqlc.Cart)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSelectedCartItems indicates an expected call of GetSelectedCartItems.
func (mr *MockStoreMockRecorder) GetSelectedCartItems(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSelectedCartItems", reflect.TypeOf((*MockStore)(nil).GetSelectedCartItems), ctx, userID)
}

// GetSession mocks base method.
func (m *MockStore) GetSession(ctx context.Context, id uuid.UUID) (sqlc.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, id)
	ret0, _ := ret[0].(sqlc.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockStoreMockRecorder) GetSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockStore)(nil).GetSession), ctx, id)
}

// GetUserByEmail mocks base method.
func (m *MockStore) GetUserByEmail(ctx context.Context, email string) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockStoreMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockStore)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockStore) GetUserByID(ctx context.Context, id int64) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockStoreMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockStore)(nil).GetUserByID), ctx, id)
}

// GetUserByPhone mocks base method.
func (m *MockStore) GetUserByPhone(ctx context.Context, phone *string) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByPhone", ctx, phone)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByPhone indicates an expected call of GetUserByPhone.
func (mr *MockStoreMockRecorder) GetUserByPhone(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByPhone", reflect.TypeOf((*MockStore)(nil).GetUserByPhone), ctx, phone)
}

// GetUserByUsername mocks base method.
func (m *MockStore) GetUserByUsername(ctx context.Context, username string) (sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockStoreMockRecorder) GetUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockStore)(nil).GetUserByUsername), ctx, username)
}

// GetUserSessions mocks base method.
func (m *MockStore) GetUserSessions(ctx context.Context, userID int64) ([]sqlc.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSessions", ctx, userID)
	ret0, _ := ret[0].([]sqlc.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSessions indicates an expected call of GetUserSessions.
func (mr *MockStoreMockRecorder) GetUserSessions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSessions", reflect.TypeOf((*MockStore)(nil).GetUserSessions), ctx, userID)
}

// GetVerificationCode mocks base method.
func (m *MockStore) GetVerificationCode(ctx context.Context, arg sqlc.GetVerificationCodeParams) (sqlc.VerificationCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerificationCode", ctx, arg)
	ret0, _ := ret[0].(sqlc.VerificationCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVerificationCode indicates an expected call of GetVerificationCode.
func (mr *MockStoreMockRecorder) GetVerificationCode(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerificationCode", reflect.TypeOf((*MockStore)(nil).GetVerificationCode), ctx, arg)
}

// IncrementProductSales mocks base method.
func (m *MockStore) IncrementProductSales(ctx context.Context, arg sqlc.IncrementProductSalesParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementProductSales", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementProductSales indicates an expected call of IncrementProductSales.
func (mr *MockStoreMockRecorder) IncrementProductSales(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementProductSales", reflect.TypeOf((*MockStore)(nil).IncrementProductSales), ctx, arg)
}

// IncrementProductViews mocks base method.
func (m *MockStore) IncrementProductViews(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementProductViews", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementProductViews indicates an expected call of IncrementProductViews.
func (mr *MockStoreMockRecorder) IncrementProductViews(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementProductViews", reflect.TypeOf((*MockStore)(nil).IncrementProductViews), ctx, id)
}

// ListFeaturedProducts mocks base method.
func (m *MockStore) ListFeaturedProducts(ctx context.Context, arg sqlc.ListFeaturedProductsParams) ([]sqlc.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFeaturedProducts", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFeaturedProducts indicates an expected call of ListFeaturedProducts.
func (mr *MockStoreMockRecorder) ListFeaturedProducts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFeaturedProducts", reflect.TypeOf((*MockStore)(nil).ListFeaturedProducts), ctx, arg)
}

// ListProducts mocks base method.
func (m *MockStore) ListProducts(ctx context.Context, arg sqlc.ListProductsParams) ([]sqlc.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockStoreMockRecorder) ListProducts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockStore)(nil).ListProducts), ctx, arg)
}

// ListProductsByCategory mocks base method.
func (m *MockStore) ListProductsByCategory(ctx context.Context, arg sqlc.ListProductsByCategoryParams) ([]sqlc.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductsByCategory", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductsByCategory indicates an expected call of ListProductsByCategory.
func (mr *MockStoreMockRecorder) ListProductsByCategory(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductsByCategory", reflect.TypeOf((*MockStore)(nil).ListProductsByCategory), ctx, arg)
}

// ListUsers mocks base method.
func (m *MockStore) ListUsers(ctx context.Context, arg sqlc.ListUsersParams) ([]sqlc.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, arg)
	ret0, _ := ret[0].([]sqlc.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockStoreMockRecorder) ListUsers(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockStore)(nil).ListUsers), ctx, arg)
}

// MarkCodeAsUsed mocks base method.
func (m *MockStore) MarkCodeAsUsed(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkCodeAsUsed", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkCodeAsUsed indicates an expected call of MarkCodeAsUsed.
func (mr *MockStoreMockRecorder) MarkCodeAsUsed(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkCodeAsUsed", reflect.TypeOf((*MockStore)(nil).MarkCodeAsUsed), ctx, id)
}

// SearchProducts mocks base method.
func (m *MockStore) SearchProducts(ctx context.Context, arg sqlc.SearchProductsParams) ([]sqlc.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchProducts", ctx, arg)
	ret0, _ := ret[0].([]sqlc.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchProducts indicates an expected call of SearchProducts.
func (mr *MockStoreMockRecorder) SearchProducts(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchProducts", reflect.TypeOf((*MockStore)(nil).SearchProducts), ctx, arg)
}

// UpdateAllCartSelected mocks base method.
func (m *MockStore) UpdateAllCartSelected(ctx context.Context, arg sqlc.UpdateAllCartSelectedParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAllCartSelected", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAllCartSelected indicates an expected call of UpdateAllCartSelected.
func (mr *MockStoreMockRecorder) UpdateAllCartSelected(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAllCartSelected", reflect.TypeOf((*MockStore)(nil).UpdateAllCartSelected), ctx, arg)
}

// UpdateCartQuantity mocks base method.
func (m *MockStore) UpdateCartQuantity(ctx context.Context, arg sqlc.UpdateCartQuantityParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartQuantity", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCartQuantity indicates an expected call of UpdateCartQuantity.
func (mr *MockStoreMockRecorder) UpdateCartQuantity(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartQuantity", reflect.TypeOf((*MockStore)(nil).UpdateCartQuantity), ctx, arg)
}

// UpdateCartSelected mocks base method.
func (m *MockStore) UpdateCartSelected(ctx context.Context, arg sqlc.UpdateCartSelectedParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCartSelected", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCartSelected indicates an expected call of UpdateCartSelected.
func (mr *MockStoreMockRecorder) UpdateCartSelected(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCartSelected", reflect.TypeOf((*MockStore)(nil).UpdateCartSelected), ctx, arg)
}

// UpdateProduct mocks base method.
func (m *MockStore) UpdateProduct(ctx context.Context, arg sqlc.UpdateProductParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockStoreMockRecorder) UpdateProduct(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockStore)(nil).UpdateProduct), ctx, arg)
}

// UpdateProductImage mocks base method.
func (m *MockStore) UpdateProductImage(ctx context.Context, arg sqlc.UpdateProductImageParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductImage", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProductImage indicates an expected call of UpdateProductImage.
func (mr *MockStoreMockRecorder) UpdateProductImage(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductImage", reflect.TypeOf((*MockStore)(nil).UpdateProductImage), ctx, arg)
}

// UpdateProductStock mocks base method.
func (m *MockStore) UpdateProductStock(ctx context.Context, arg sqlc.UpdateProductStockParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductStock", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProductStock indicates an expected call of UpdateProductStock.
func (mr *MockStoreMockRecorder) UpdateProductStock(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductStock", reflect.TypeOf((*MockStore)(nil).UpdateProductStock), ctx, arg)
}

// UpdateUser mocks base method.
func (m *MockStore) UpdateUser(ctx context.Context, arg sqlc.UpdateUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockStoreMockRecorder) UpdateUser(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockStore)(nil).UpdateUser), ctx, arg)
}

// UpdateUserLastLogin mocks base method.
func (m *MockStore) UpdateUserLastLogin(ctx context.Context, arg sqlc.UpdateUserLastLoginParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserLastLogin", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserLastLogin indicates an expected call of UpdateUserLastLogin.
func (mr *MockStoreMockRecorder) UpdateUserLastLogin(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserLastLogin", reflect.TypeOf((*MockStore)(nil).UpdateUserLastLogin), ctx, arg)
}

// UpdateUserPassword mocks base method.
func (m *MockStore) UpdateUserPassword(ctx context.Context, arg sqlc.UpdateUserPasswordParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPassword", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPassword indicates an expected call of UpdateUserPassword.
func (mr *MockStoreMockRecorder) UpdateUserPassword(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPassword", reflect.TypeOf((*MockStore)(nil).UpdateUserPassword), ctx, arg)
}

// UpdateUserStatus mocks base method.
func (m *MockStore) UpdateUserStatus(ctx context.Context, arg sqlc.UpdateUserStatusParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserStatus", ctx, arg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserStatus indicates an expected call of UpdateUserStatus.
func (mr *MockStoreMockRecorder) UpdateUserStatus(ctx, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserStatus", reflect.TypeOf((*MockStore)(nil).UpdateUserStatus), ctx, arg)
}

// VerifyUserEmail mocks base method.
func (m *MockStore) VerifyUserEmail(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUserEmail", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyUserEmail indicates an expected call of VerifyUserEmail.
func (mr *MockStoreMockRecorder) VerifyUserEmail(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUserEmail", reflect.TypeOf((*MockStore)(nil).VerifyUserEmail), ctx, id)
}

// VerifyUserPhone mocks base method.
func (m *MockStore) VerifyUserPhone(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUserPhone", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyUserPhone indicates an expected call of VerifyUserPhone.
func (mr *MockStoreMockRecorder) VerifyUserPhone(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUserPhone", reflect.TypeOf((*MockStore)(nil).VerifyUserPhone), ctx, id)
}
